### ISSUE TITLE
Bug: Ergebnis 0.0

### ISSUE THREAD

**Issue by TobiasSMI** [Syoxz/Calculator#1]
### Mein Taschenrechner spukt mir ein etwas anderes Ergebnis aus:
![image](https://user-images.githubusercontent.com/41923750/161519863-35428181-6830-4f42-91a0-4ac5f9f5125d.png)

> In deinem Taschenrechner habe ich Folgendes erhalten:
![image](https://user-images.githubusercontent.com/41923750/161519739-69232fef-a349-4b79-92ad-0eadc739a676.png)
![image](https://user-images.githubusercontent.com/41923750/161519769-84613752-6e7c-4919-9c8d-cd6a0782d28c.png)

**Comment by Syoxz** [comment]
Sollte gefixed sein

**Comment by TobiasSMI** [comment]
Test i.O.
